<?php

function ebrides_form_alter(&$form, &$form_state, $form_id) {
	if ($form_id == 'webform_client_form_19') {
		$form['#attached']['js'][] = drupal_get_path('module', 'ebrides'). '/ebrides.js';
	}
}

function ebrides_preprocess_webform_confirmation(&$vars) {

	if ($vars['node']->nid == 19) {
		module_load_include('inc', 'webform', 'includes/webform.submissions');
		$submission = webform_get_submission($vars['node']->nid, $vars['sid']);

		$form = $vars['node']->webform;

		$email = "ebrides@ymail.com";
		$name = "eBrides Payment";
		$field_count = 10;

		$location_price = 60;
		$category_price = 60;
		$categories = _map_webform_field($form, $submission, 'categories');

		$locations = array();
		for($i = 1; $i < 10; $i++) {
			$locations[] = _map_webform($form, $submission, 'location'. $i);
		}

		$locations = array_filter($locations, 'strlen');
		$amount = 99 +
			max(0, (count($locations) - 1)*$location_price) +
			max(0, (count($categories) - 1)*$category_price);


		$confirmation = check_markup($vars['node']->webform['confirmation'], $vars['node']->webform['confirmation_format'], '', TRUE);
		$confirmation .= <<<html
<form action="https://www.paypal.com/cgi-bin/webscr" method="get">
    <input type="hidden" name="cmd" value="_xclick" />
    <input type="hidden" name="business" value="$email" />
    <input type="hidden" name="lc" value="CA" />
    <input type="hidden" name="item_name" value="$name" />

    <input type="hidden" name="amount" value="$amount" />
    <input type="submit" value="Pay \$$amount using Paypal" />

    <input type="hidden" name="currency_code" value="CAD" />
    <input type="hidden" name="button_subtype" value="products" />
    <input type="hidden" name="no_note" value="1" />
    <input type="hidden" name="no_shipping" value="1" />
</form>
html;

		// Strip out empty tags added by WYSIWYG editors if needed.
		$vars['confirmation_message'] = strlen(trim(strip_tags($confirmation))) ? $confirmation : '';
	}
}

function _map_webform_field($form, $submission, $field) {
	$mapping = array();
	$components = $form['components'];
	$values = $submission->data;

	foreach ($components as $i => $component) {
		$key = $component['form_key'];
		$mapping[$key] = $i;
	}

	return $values[$mapping[$field]]['value'];
}

function _map_webform($form, $submission, $field) {
	$field = _map_webform_field($form, $submission, $field);
	return $field[0];
}

function ebrides_views_pre_render(&$view) {
	if ($view->name == 'business_listings') {
		$cid = isset($view->filter['field_category_tid'])? $view->filter['field_category_tid'] : false;
		$category = false;
		$rid = isset($view->filter['field_regions_tid'])? $view->filter['field_regions_tid'] : false;
		$region = false;

		if ($cid) {
			$cid = count($cid->value)? $cid->value[0] : false;

			if ($cid) {
				$category = taxonomy_term_load($cid);

				if ($category) {
					$category = $category->name;
				}
			}
		}
		if ($rid) {
			$rid = count($rid->value)? $rid->value[0] : false;

			if ($rid) {
				$region = taxonomy_term_load($rid);

				if ($region) {
					$region = $region->name;
				}
			}
		}

		$title = array($region, $category);
		$title = implode(', ', array_filter($title, 'strlen'));
		$title = array('Business Listings', $title);
		$title = implode(' - ', array_filter($title, 'strlen'));

		$view->build_info['title'] = $title;
	}
}